services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend_python
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "3000:3000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend_python:/app
    env_file:
      - ./backend_python/.env 